movie_project/movie_app/urls.py
from django.contrib.admin import views
from django.urls import path
from . import views
app_name='movie_app'

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie_project/movie_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models
from django.db.models import IntegerField, ImageField


# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_project/movie_app/forms.py
from django import forms
from . models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from . models import Movie

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        "movie_list":movie
    }

    return render(request,"index.html",context)

def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,"delete.html")

movie_project/templates/add.html
{% extends 'base.html' %}
{% block body %}

   <form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}

      <input type="text" name="name" placeholder="Enter the movie name">
      <input type="text" name="desc" placeholder="Enter the movie description">
      <input type="text" name="year" placeholder="Enter the movie released year">
      <input type="file" name="img">
      <input type="submit">
  </form>

 {% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
   Movie Online Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Do you want to delete?
    <input type="submit">
</form>

movie_project/templates/details.html
{% extends 'base.html' %}
{% block body %}


<div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="{{movie.img.url}}" width="300" height="300">
      </div>
      <div class="col-md-6">
        <h6>{{movie.name}}</h6>
        <h4>{{movie.desc}}</h4>
        <h6>{{movie.year}}</h6>
       <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a><br>
       <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a><br>
      </div>
    </div>
</div>


{% endblock %}

movie_project/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}




<div class="container">
    <div class=" row">
        {% for i in movie_list %}
        <div class="col-md-4">
           <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{i.img.url}}" alt="" height="250px" >
             <div class="card-body">
               <h5 class="card-title">{{i.name}}</h5>
               <p class="card-text">{{i.desc}}</p>
               <a href="{% url  'movie_app:details' i.id %}" class="btn btn-primary">Go somewhere</a>
             </div>
           </div>
        </div>


        {% endfor %}
    </div>
</div>

<img src="{{i.img.url}}" width="100" height="100">
<a href=>{{i.name}}<br>

{% endblock %}